name: pencil_kit
description: A Flutter plugin that provides a iOS PencilKit widget on iOS.
repository: https://github.com/mj-studio-library/flutter-pencilkit
homepage: https://github.com/mj-studio-library/flutter-pencilkit
version: 0.0.4

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PencilKitPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  yaml:

